# Generated by Django 6.0.3 on 2026-03-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('link_text', models.CharField(blank=True, max_length=50)),
                ('link_url', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('subheading', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('bg_color', models.CharField(default='#0a1628', max_length=7)),
                ('cta_text', models.CharField(default='Shop Now', max_length=50)),
                ('cta_url', models.CharField(default='/shop/', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OrderStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='01', max_length=4)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='⚽', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'How to Order Step',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='JMD Promotions', max_length=100)),
                ('site_tagline', models.CharField(default='Premium Teamwear & Sportswear', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('primary_color', models.CharField(default='#d62828', max_length=7)),
                ('secondary_color', models.CharField(default='#0a1628', max_length=7)),
                ('accent_color', models.CharField(default='#f0a500', max_length=7)),
                ('hero_heading', models.CharField(default='Kit Your Whole Team Out.', max_length=200)),
                ('hero_subheading', models.TextField(default='Custom football kits, tracksuits, training gear and off-field apparel — fully branded with your club colours.')),
                ('hero_cta_text', models.CharField(default='Shop Teamwear', max_length=50)),
                ('hero_cta2_text', models.CharField(default='View 2026 Catalogue', max_length=50)),
                ('hero_cta2_url', models.CharField(blank=True, default='#', max_length=500)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('ticker_text', models.TextField(default='Free Branding on Orders Over R5,000 | 2026 Catalogue Now Available | Nationwide Delivery | Custom Name & Number Printing | Club & School Packages Available')),
                ('stat1_number', models.CharField(default='800+', max_length=20)),
                ('stat1_label', models.CharField(default='Teams Kitted', max_length=50)),
                ('stat2_number', models.CharField(default='15', max_length=20)),
                ('stat2_label', models.CharField(default='Years Experience', max_length=50)),
                ('stat3_number', models.CharField(default='5 Day', max_length=20)),
                ('stat3_label', models.CharField(default='Avg Turnaround', max_length=50)),
                ('stat4_number', models.CharField(default='100%', max_length=20)),
                ('stat4_label', models.CharField(default='SA Based & Owned', max_length=50)),
                ('phone', models.CharField(default='+27 11 000 0000', max_length=30)),
                ('whatsapp_number', models.CharField(default='27110000000', max_length=20)),
                ('email', models.EmailField(default='info@jmdprofessionals.co.za', max_length=254)),
                ('address', models.CharField(default='Johannesburg, Gauteng, South Africa', max_length=200)),
                ('hours', models.CharField(default='Mon-Fri: 08:00 - 17:00', max_length=100)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('meta_title', models.CharField(default='JMD Promotions - Premium Teamwear & Sportswear', max_length=200)),
                ('meta_description', models.TextField(default="South Africa's trusted custom teamwear specialists.")),
                ('footer_about', models.TextField(default="South Africa's trusted custom teamwear specialists. Serving clubs, schools and academies since 2009 - based in Johannesburg, shipping nationwide.")),
                ('footer_copyright', models.CharField(default='2026 JMD Promotions. All rights reserved.', max_length=200)),
                ('catalogue_pdf', models.FileField(blank=True, null=True, upload_to='catalogues/')),
                ('catalogue_banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('club_or_school', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
